name: Release

on:
  push:
    branches: ["main"]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    environment: secrets
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Setup vsce
        run: npm install -g @vscode/vsce

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          
      - name: Install Nox
        run: pip install nox

      - name: Update package.json Version
        run: |
          TIMESTAMP=$(date -u +'%Y.%m.%d')
          npm version $TIMESTAMP --no-git-tag-version
          
          echo "NEW_VERSION=$TIMESTAMP" >> $GITHUB_ENV

      - name: Install and Update Node Dependencies (npm update)
        run: npm update

      - name: Prepare Python Environment with Nox
        run: nox --session setup

      - name: Build Package with Nox
        run: nox --session build_package

      - name: "Publish Release on VS Code Marketplace"
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Commit release changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
            commit_message: Release version ${{ env.NEW_VERSION }}
